// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB03RayfyFDKPSmP7-MDcysC9Nix-BroU',
    appId: '1:361796956966:web:9dbaac1d48d2ded0f247e7',
    messagingSenderId: '361796956966',
    projectId: 'puskesmas-c3934',
    authDomain: 'puskesmas-c3934.firebaseapp.com',
    storageBucket: 'puskesmas-c3934.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx7iRXmWWxzlXVzVEPZF-erqriYMBvwrU',
    appId: '1:361796956966:android:97cb66de496f4ceef247e7',
    messagingSenderId: '361796956966',
    projectId: 'puskesmas-c3934',
    storageBucket: 'puskesmas-c3934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQAUXOgNSdANCuoenuDAGCYm3EWBablQ',
    appId: '1:361796956966:ios:061ef408a7984891f247e7',
    messagingSenderId: '361796956966',
    projectId: 'puskesmas-c3934',
    storageBucket: 'puskesmas-c3934.firebasestorage.app',
    iosBundleId: 'com.example.puskesmas',
  );
}
